edition = "2018"
fn_args_layout = "Tall"
force_explicit_abi = true
hard_tabs = true
max_width = 110
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 3
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# unstable options
#binop_separator = "Front"
#blank_lines_lower_bound = 0
#blank_lines_upper_bound = 1
#brace_style = "SameLineWhere"
#color = "Auto"
#combine_control_expr = true
#comment_width = 110
#condense_wildcard_suffixes = false
#control_brace_style = "AlwaysSameLine"
#disable_all_formatting = false
#empty_item_single_line = true
#enum_discrim_align_threshold = 0
#error_on_line_overflow = false
#error_on_unformatted = false
#fn_single_line = false
#force_multiline_blocks = false
#format_code_in_doc_comments = true
#format_macro_matchers = true
#format_macro_bodies = true
#format_strings = false
#hide_parse_errors = false
#imports_indent = "Block"
#imports_layout = "HorizontalVertical"
